framework:
    messenger:
        failure_transport: failed

        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(resolve:MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
#                    use_notify: true
#                    check_delayed_interval: 60000
                    exchange:
                        # Название точки обмена
                        name: messages
                    queues:
                        # Название очереди
                        messages: ~
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            App\Message\AsyncMessageInterface: async