<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVTjLkC3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVTjLkC3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVTjLkC3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVTjLkC3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVTjLkC3\App_KernelDevDebugContainer([
    'container.build_hash' => 'VTjLkC3',
    'container.build_id' => '2dcd4159',
    'container.build_time' => 1717749733,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVTjLkC3');
